# Generated by Django 5.2.5 on 2025-12-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_alter_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=200, unique=True, verbose_name='Cliente'),
        ),
    ]
