# Generated by Django 5.2.5 on 2025-12-02 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0003_alter_cliente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.cliente', verbose_name='Hospital'),
        ),
    ]
