# Generated by Django 5.2.5 on 2025-12-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0004_alter_relatorio_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='compressor',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
