# Generated by Django 5.2.5 on 2025-12-02 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0005_relatorio_compressor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='compressor',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='relatorio.imagens'),
        ),
    ]
