# Generated by Django 5.2.5 on 2025-12-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0006_imagens_remove_relatorio_compressor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='foto',
        ),
        migrations.AddField(
            model_name='imagens',
            name='relatorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='relatorio.relatorio'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='relatorios/'),
        ),
    ]
