# Generated by Django 5.2.5 on 2025-12-02 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0007_remove_relatorio_foto_imagens_relatorio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagens',
            new_name='Imagem',
        ),
    ]
