FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    cron \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Executa o comando todo dia às 00:05
RUN echo "5 0 * * * cd /app && python backend/manage.py monthly_consumption >> /var/log/consumo_mensal.log 2>&1" \
    > /etc/cron.d/consumo-mensal

RUN chmod 0644 /etc/cron.d/consumo-mensal \
    && crontab /etc/cron.d/consumo-mensal

CMD ["cron", "-f"]