FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Coleta arquivos estáticos
RUN python backend/manage.py collectstatic --noinput

EXPOSE 8000

CMD ["sh", "-c", "python backend/manage.py makemigrations && python backend/manage.py migrate && exec gunicorn --chdir /app/backend --bind 0.0.0.0:8000 --workers 3 --timeout 120 monitoramento.wsgi:application"]