FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    cron \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Configuração do cron
RUN echo "SHELL=/bin/sh" > /etc/cron.d/consumo-mensal && \
    echo "PATH=/usr/local/bin:/usr/bin:/bin" >> /etc/cron.d/consumo-mensal && \
    echo "5 0 * * * cd /app && /usr/local/bin/python backend/manage.py monthly_consumption >> /var/log/consumo_mensal.log 2>&1" >> /etc/cron.d/consumo-mensal

# Permissão e instalação do cron
RUN chmod 0644 /etc/cron.d/consumo-mensal && \
    crontab /etc/cron.d/consumo-mensal

# Mantém o cron rodando em foreground
CMD ["cron", "-f"]