from typing import Protocol
from .entities import Fault, Connection

class AlertRepository(Protocol):
    def save(self, fault: Fault) -> None: ...
    def remove(self, fault: Fault) -> None: ...

class Handle(Protocol):
    @classmethod
    def create_message(cls, fault: Fault)-> str: ...

    @classmethod
    def create_recover_message(cls, fault: Fault)-> str: ...

    @classmethod
    def create_connection_message(cls, connection: Connection) -> str: ...

class Sender(Protocol):
    @staticmethod
    def send_message(chat_id, text) -> None: ...

    def send_fault(self, fault: Fault, recover: bool = False) -> None: ...

def get_chat_id(name): ...