# Generated by Django 5.2.5 on 2026-07-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_hospitalgroup_hospital_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='multiplicador_acumulado',
            field=models.FloatField(default=1.0),
        ),
    ]
