# Generated by Django 5.2.5 on 2026-07-15 14:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_hospital_multiplicador_acumulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='multiplicador_acumulado',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, verbose_name='Multiplicador do acumulado'),
        ),
    ]
