# Generated by Django 5.2.5 on 2026-07-16 11:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_hospital_multiplicador_acumulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='offset_acumulado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='hospital',
            name='offset_pressao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='hospital',
            name='offset_pressao_produto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='hospital',
            name='offset_pureza',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='hospital',
            name='soma_pressao',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8, verbose_name='Multiplicador da pressão'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='soma_pressao_produto',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8, verbose_name='Multiplicador da pressão do produto'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='soma_pureza',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8, verbose_name='Multiplicador da pureza'),
        ),
    ]
