# Generated by Django 5.2.5 on 2026-07-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_hospital_offset_acumulado_hospital_offset_pressao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='soma_pressao',
            new_name='multiplicador_pressao',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='soma_pressao_produto',
            new_name='multiplicador_pressao_produto',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='soma_pureza',
            new_name='multiplicador_pureza',
        ),
    ]
