# Generated by Django 5.2.5 on 2026-08-11 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_soma_pressao_hospital_multiplicador_pressao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('product_pressure', models.FloatField(blank=True, null=True)),
                ('purity', models.FloatField(blank=True, null=True)),
                ('flow', models.FloatField(blank=True, null=True)),
                ('accumulated', models.FloatField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_telemetria', to='dashboard.hospital')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['hospital', '-timestamp'], name='dashboard_t_hospita_ac73f0_idx'), models.Index(fields=['timestamp'], name='dashboard_t_timesta_9bea83_idx')],
                'constraints': [models.UniqueConstraint(fields=('hospital', 'timestamp'), name='unique_hospital_telemetry_timestamp')],
            },
        ),
    ]
