# Generated by Django 5.2.5 on 2026-08-12 14:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_telemetryhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('consumo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('acumulado_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('acumulado_final', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_mensais', to='dashboard.hospital')),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'constraints': [models.UniqueConstraint(fields=('hospital', 'ano', 'mes'), name='unique_hospital_monthly_consumption')],
            },
        ),
    ]
