# Generated by Django 5.2.5 on 2026-07-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('dashboard', '0006_hospitalgroup_hospital_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.hospitalgroup'),
        ),
    ]
